source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RaceTracker_Example', :exclusive => true do
  pod "RaceTracker", :path => "../"
end

target 'RaceTracker_Tests', :exclusive => true do
  pod "RaceTracker", :path => "../"

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', "2.0.0-rc.3"
end
